# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: "en-US"
tone_instructions: "Be concise and constructive. Focus on bugs, security issues, and performance improvements."

early_access: false

reviews:
  profile: "chill"
  request_changes_workflow: false
  high_level_summary: true
  high_level_summary_placeholder: "@coderabbitai summary"
  auto_title_placeholder: "@coderabbitai"
  poem: false
  review_status: true
  collapse_walkthrough: false
  sequence_diagrams: true
  changed_files_summary: true
  labeling_instructions: []
  path_filters: []
  path_instructions:
    - path: "backend/**/*.py"
      instructions: |
        Review Python code for FastAPI best practices, proper Pydantic schema usage,
        SQLAlchemy patterns, and proper error handling.
    - path: "frontend/**/*.{ts,tsx}"
      instructions: |
        Review TypeScript/React code for type safety, proper hook usage,
        component patterns, and Next.js best practices.
    - path: "**/*.test.*"
      instructions: |
        Review test coverage, edge cases, and proper assertion patterns.
  abort_on_close: true
  auto_review:
    enabled: true
    auto_incremental_review: true
    ignore_title_keywords:
      - "WIP"
      - "DO NOT MERGE"
    drafts: false
    base_branches:
      - "main"

chat:
  auto_reply: true

knowledge_base:
  opt_out: false
  learnings:
    scope: "auto"
  issues:
    scope: "auto"
  jira:
    usage: "auto"
  linear:
    usage: "auto"
  pull_requests:
    scope: "auto"
